# netlify.toml
[build]
  command = "" # No build command needed for a static site
  publish = "src" # Serve files from the 'src' directory
  functions = "netlify/functions" # Directory for serverless functions
