# netlify.toml - V3 (Corrected for Asset Handling)

[build]
  # This tells Netlify that your website's files are in the root directory.
  publish = "."
  functions = "api/"

[functions]
  node_bundler = "esbuild"

# This rule MUST come first. It directs all API calls to your functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# --- THE CRITICAL FIX IS HERE ---
# This is the corrected Single-Page Application (SPA) rule.
# It tells Netlify to redirect any path that is NOT a file to index.html.
# This allows requests for /style.css, /main.js, etc., to work correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
