[build]
  # THE FIX: This command forces Netlify to install the dependencies from package.json.
  command = "npm install"
  
  # This tells Netlify where your serverless functions are.
  functions = "api/"

# This rule makes sure your pages work correctly when you refresh them.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
