# netlify.toml - V4 (The Correct, Robust Configuration)

[build]
  # This tells Netlify where your publish directory is.
  publish = "."
  functions = "api/"

[functions]
  node_bundler = "esbuild"

# Rule for API functions (must be first)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# This is the correct Single-Page Application (SPA) fallback rule.
# It only serves index.html for paths that do NOT match an existing file.
# This allows /style.css, /main.js, etc., to be served correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
