[build]
  # This is the only instruction Netlify needs.
  # It tells Netlify that your serverless functions are in this directory.
  functions = "api/"

# This rule makes your pages work correctly when you refresh them.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
