[build]
  # This tells Netlify where your serverless functions are located.
  # Netlify will automatically find the package.json inside and install dependencies.
  functions = "api/"

# This rule makes your pages work correctly when you refresh them.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
