[functions]
  directory = "netlify/functions/"```
5.  Scroll down and **"Commit new file"**. This tells Netlify, "Look for any serverless functions inside a folder named `netlify/functions`."

**Step 2: Create the Netlify Function File**

Now we create the "secret agent" function itself.

1.  Go back to the main page of your repository.
2.  Tap **"Add file"** -> **"Create new file"**.
3.  This time, we need to create a folder structure. In the filename box, type this exactly:
    `netlify/functions/getMovies.js`
    *(When you type the `/`, GitHub will automatically create the folders for you).*
4.  Now, copy and paste the following JavaScript code into the file. This is the server-side code for your function.

```javascript
// This is the server-side Netlify Function

exports.handler = async function(event, context) {
    // 1. Get the secret API key from Netlify's environment variables
    const apiKey = process.env.TMDB_API_KEY;

    if (!apiKey) {
        return {
            statusCode: 500,
            body: JSON.stringify({ message: "API key is not set." })
        };
    }

    // 2. The API URL to fetch trending movies
    const apiUrl = `https://api.themoviedb.org/3/trending/movie/week?api_key=${apiKey}`;

    try {
        // 3. Fetch data from the TMDb API (this happens on the server)
        const response = await fetch(apiUrl);
        const data = await response.json();

        // 4. Send the successful results back to the browser
        return {
            statusCode: 200,
            body: JSON.stringify(data)
        };
    } catch (error) {
        // Handle any errors
        return {
            statusCode: 500,
            body: JSON.stringify({ message: error.message })
        };
    }
};
