# netlify.toml - The Definitive, Robust Configuration V2

[build]
  functions = "api/"

# --- NEW & CRITICAL ---
# This section tells Netlify to use the 'esbuild' bundler, which is fast and
# correctly packages external Node.js dependencies for your functions.
[functions]
  node_bundler = "esbuild"

# This rule MUST come first. It directs all API calls to your functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# This is the fallback rule for your single-page application routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 # Changed to 200 for better SPA routing
